CREATE DATABASE HETHONGSINHCAUHOITUDONG;
GO

USE HETHONGSINHCAUHOITUDONG;
GO

CREATE TABLE VaiTro (
    VaiTroId INT PRIMARY KEY,
    TenVaiTro NVARCHAR(50)
);

INSERT INTO VaiTro (VaiTroId, TenVaiTro) VALUES (1, 'Admin'), (2, 'Giảng viên'), (3, 'Sinh viên');

CREATE TABLE NguoiDung (
    NguoiDungId INT IDENTITY(1,1) PRIMARY KEY,
    HoTen NVARCHAR(255) NOT NULL,
    Email VARCHAR(255) UNIQUE NOT NULL,
    MatKhauHash VARCHAR(255) NOT NULL,
    VaiTroId INT FOREIGN KEY REFERENCES VaiTro(VaiTroId)
);
GO
